### ISSUE TITLE
better example

### ISSUE THREAD

**Issue by jfairley** [codearoni/zxp-provider#1]
Can you give a better example of how to use this?

What is equivalent to: `ZXPSignCmd -sign build my.zxp cert.p12 password`?

Also, does it support `ZXPSignCmd -selfSignedCert`?

**Comment by codearoni** [comment]
zxp-provider simply provides a path to the executable, so yes you can use -selfSignedCert.

Using it is no different than any other child_process that you could start with node.js (see node's docs on how to spawn a child_process)

I think the quickest example would be in gizmo's gulpfile: https://github.com/codearoni/generator-gizmo/blob/master/app/templates/gulpfile.js#L89 (where zxp == binPath).

Gizmo will eventually utilize zxp-provider. No time at the moment to push through that change though.

**Comment by codearoni** [comment]
@jfairley, so in the process of trying to sanely integrate ZXPSignCmd into a build chain, I ended up creating another module with an actual interface: https://github.com/codearoni/zxp-sign-cmd

Is that what you're looking for?

**Comment by jfairley** [comment]
YES! https://github.com/codearoni/zxp-sign-cmd is exactly what I was thinking. 

I mean I already have all this set up and working with shell scripts, but I like what you've done. Mostly because, no matter what tool I find myself using, executing the signer is always awkward to express in JS. Take your 10-line gulp task as an example.

Very cool. 👍

**Comment by codearoni** [comment]
Right on. Yea I've found that executable's can be troublesome to maintain in node child_processes when they're not wrapped in some fashion - especially when the exe is expecting arguments in a specific order, like ZXPSignCmd does. 

I contemplated slapping it in here, but decided to keep it pure so that anyone could use zxp-provider to access the raw binary, should they choose. cheers
